---
id: rubykaigi-2013
base_name: be-a-library-developer
tags:
- rabbit
- rubykaigi
- library
presentation_date: 2013/06/01
version: 2013.6.1.8
licenses:
- CC BY-SA 3.0
slideshare_id: rubykaigi-2013
speaker_deck_id: be-a-library-developer
ustream_id: 33615831
vimeo_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
